'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8943
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Remisiones.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BorrarFila28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BorrarFila28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BorrarFila40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BorrarFila40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Búsqueda48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Búsqueda48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonlog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonlog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Carro100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Carro52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Carro64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CirculoPlus48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CirculoPlus48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CirculoPlus481() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CirculoPlus481", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CirculPlus68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CirculPlus68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Conductor100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Conductor100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conexion48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conexion48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conexion68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conexion68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Country_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Country-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disconexion48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconexion48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disconexion68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconexion68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disconexion681() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconexion681", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property driver_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Eliminar42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eliminar42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Eliminar45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eliminar45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Eliminar48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eliminar48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farm_with_silo_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farm-with-silo-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property farmer_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_búsqueda_de_propiedad_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-búsqueda-de-propiedad-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_coffee_beans_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-coffee-beans-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_driver_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-driver-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_farm_with_silo_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-farm-with-silo-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_paste_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-paste-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_plus_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-plus-36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_user_account_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-user-account-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_user_account_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-user-account-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_user_shield_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-user-shield-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8paste_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8paste-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imprimir48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imprimir48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property llave01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("llave01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property llave02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("llave02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property llave021() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("llave021", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoMakupCoffeSF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoMakupCoffeSF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoMakupCoffesinfondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoMakupCoffesinfondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lupa32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lupa321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lupa322() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa322", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lupa323() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa323", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Makusplas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Makusplas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Makusplas1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Makusplas1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mundi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mundi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Opera_glasses_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Opera-glasses-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pesaje32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pesaje32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Print48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Print68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property productor100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productor100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Recepcion_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recepcion-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SALIR02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SALIR02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save481() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save481", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save4811() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save4811", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save482() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save482", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save4821() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save4821", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Security01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Security01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sin_tilo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin tilo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Teclado32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teclado32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tikect48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tikect48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tikect68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tikect68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Transit_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transit-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trolley_48d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trolley-48d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UseersLog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UseersLog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weight_station_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weight-station-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
